[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "npm run railway:start"
healthcheckPath = "/healthz"
healthcheckTimeout = 300
restartPolicyType = "on-failure"
restartPolicyMaxRetries = 3

[env]
N8N_ENCRYPTION_KEY = "${N8N_ENCRYPTION_KEY}" 